# Alacritty Configuration file

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["-l"]
program = "zsh"

[window]
option_as_alt = "Both"
padding = { x = 6, y = 0 }
opacity = 1.0

[scrolling]
history = 50000
multiplier = 3

[colors]
line_indicator = { foreground = "#424242", background = "#1e1e1e" }
footer_bar = { foreground = "#cb775d", background = "#161616" }
selection = { text = "#cb775d", background = "#424242"}

[colors.primary]
foreground = "#eceff4"
background = "#1e1e1e"
dim_foreground = "#e5e9f0"
bright_foreground = "#f8f8ff"

[colors.search]
matches = { foreground = "#101010", background = "#cb775d" }
focused_match = { foreground = "#101010", background = "#b74e58" }

[colors.hints]
start = { foreground = "#161616", background = "#cb775d" }
end = { foreground = "#161616", background = "#cb775d" }

[colors.normal]
black = "#141414"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#e5e9f0"

[colors.bright]
black = "#626262"
red = "#c5727a"
green = "#b1c89d"
yellow = "#efd49f"
blue = "#88c0d0"
magenta = "#be9db8"
cyan = "#9fc6c5"
white = "#eceff4"

[colors.dim]
black = "#101010"
red = "#b74e58"
green = "#97b67c"
yellow = "#e7c173"
blue = "#5e81ac"
magenta = "#a97ea1"
cyan = "#80b3b2"
white = "#d8dee9"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[[hints.enabled]]
command = "xdg-open" # "open" On macOS or "xdg-open" on Linux
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "H", mods = "Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|https://|http://|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints]
alphabet = "ftluresdh"

[keyboard]
bindings = [
    { key = "C", mods = "Alt", action = "Copy" },
    { key = "P", mods = "Alt", action = "Paste" },
    { key = "/", mods = "Alt", action = "SearchForward" },
    { key = "?", mods = "Alt", action = "SearchBackward" },
    # Vi mode bindings
    { key = "J", mods = "Shift", mode = "Vi|~Search", action = "SearchPrevious" },
    { key = "V", mods = "Alt|Shift", action = "ToggleViMode" },
    { key = "L", mode = "Vi|~Search", action = "WordRightEnd" },
    { key = "H", mode = "Vi|~Search", action = "ToggleViMode" },
    { key = "J", mode = "Vi|~Search", action = "SearchNext" },
    { key = "M", mode = "Vi|~Search", action = "Left" },
    { key = "N", mode = "Vi|~Search", action = "Down" },
    { key = "E", mode = "Vi|~Search", action = "Up" },
    { key = "I", mode = "Vi|~Search", action = "Right" },
]
