[colors.primary]
foreground = "#eceff4"
background = "#1e1e1e"
dim_foreground = "#e5e9f0"
bright_foreground = "#f8f8ff"

[colors.normal]
black = "#141414"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#e5e9f0"

[colors.bright]
black = "#626262"
red = "#c5727a"
green = "#b1c89d"
yellow = "#efd49f"
blue = "#88c0d0"
magenta = "#be9db8"
cyan = "#9fc6c5"
white = "#eceff4"

[colors.dim]
black = "#101010"
red = "#b74e58"
green = "#97b67c"
yellow = "#e7c173"
blue = "#5e81ac"
magenta = "#a97ea1"
cyan = "#80b3b2"
white = "#d8dee9"
